-- Add General Readings form table
CREATE TABLE IF NOT EXISTS `form_general_readings` (
`id`                bigint(20)      NOT NULL auto_increment,
`uuid`              binary(16)      DEFAULT NULL,
`date`              datetime        default NULL,
`pid`               bigint(20)      default 0,
`user`              varchar(255)    default NULL,
`groupname`         varchar(255)    default NULL,
`authorized`        tinyint(4)      default 0,
`activity`          tinyint(4)      default 0,
`daily_fluid_intake` FLOAT(8,2)     default 0,
`daily_protein_intake` FLOAT(8,2)   default 0,
`shower`            TINYINT(1)      default 0,
`sponge_bath`       TINYINT(1)      default 0,
`walking`           TINYINT(2)      default 0,
`am_fasting_glucose` FLOAT(5,2)     default 0,
`hs_fasting_glucose` FLOAT(5,2)    default 0,
`energy`            TINYINT(2)      default 0,
`sleep_pattern`     TINYINT(2)     default 0,
`stress_level`      TINYINT(2)     default 0,
`pain`              TINYINT(2)     default 0,
`abdominal_pain`    TINYINT(2)     default 0,
`appetite`          TINYINT(2)     default 0,
`bowel_movements`   TINYINT(2)     default 0,
`fatigue`           TINYINT(2)     default 0,
`note`              VARCHAR(255)   default NULL,
PRIMARY KEY (id),
UNIQUE KEY `uuid` (uuid)
) ENGINE=InnoDB;
